name: stryker

on:
  push:
    branches:
      - stryker
  workflow_dispatch:

jobs:

  stryker:
    name: stryker
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          npm install
          stryker run
