name: VariaMosPLE_TESTS

on:
  push:
    branches:
      - CI_test
  workflow_dispatch:

jobs:


  start_application:
    name: Starting application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Start
        run: |
          npm install
          npm start       

  run_unit_tests:
    name: Running unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: UT
        run: |
          npm install
          npm test -- --coverage --detectOpenHandles --watchAll --forceExit

  run_integration_tests:
    name: Running integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: IT
        run: |
          npm install  
          npx cypress run

        
