name: VariaMosPLE_TESTS

on:
  push:
    branches:
      - CI_test
  workflow_dispatch:

jobs:

  running_tests:
    name: Running Tests Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: |
          npm start
          npm test -- --coverage --watchAll
          npx cypress run 

        
